name: free_play_app
description: 'A Flutter Player App '
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk:  '>=3.10.0 <4.0.0'
  flutter: '>=3.38.0'

dependencies:
  flutter:
    sdk: flutter
  # 状态管理
  signals_flutter: ^6.3.0
  signals_hooks: ^0.4.0
  flutter_hooks: ^0.21.3+1
  # 网络请求
  dio: ^5.9.0
  flutter_carousel_widget: ^3.1.0
  # 播放器
  better_player_plus: ^1.1.5
  # 路由管理
  go_router: ^17.0.1
  # JSON 序序化
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  url_launcher: ^6.3.2
  line_icons: ^2.0.3
  flutter_svg: ^2.2.1
  lottie: ^3.3.2
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  # 图片处理
  cached_network_image: ^3.4.1

  injectable: ^2.7.1+4
  get_it: ^9.2.0
  pretty_dio_logger: ^1.4.0
  # 屏幕适配
  #  flutter_screenutil: ^5.9.0
  dio_smart_retry: ^7.0.1
  animations: ^2.1.1
  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  #  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  injectable_generator: ^2.12.0
  build_runner: ^2.10.5
  freezed: ^3.2.4

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/
    - assets/json/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - fonts/TrajanPro_Bold.ttf
  #         weight: 700
